config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'user_sessions/new'
  get 'user_sessions/destroy'

  get 'login', to: 'user_sessions#new'

  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'

  resources :students do
    resources :attendances, only: [:create]
    resources :comments, only: [:create] do
      post 'likes/toggle_comment_like'
      resources :answers, only: [:create]
    end
  end

  resources :users do
    patch 'change_active', to: 'users#change_active'
  end

  resources :posts, only: [:create] do
    post 'likes/toggle_post_like'
    post 'answers/create_post'
  end
end

app/models/comment.rb
class Comment < Publication
  belongs_to :student
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_student, only: %i[create]

  def create
    @comment = @student.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to student_path(@student), notice: t('.notice')
    else
      redirect_to student_path(@student), warning: t('.warning')
    end
  end

  private

  def set_student
    @student = Student.find(params[:student_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :stand_out, files: [])
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment, class: featured ? 'comment featured' : 'comment' do %>
  <div class='comment-header'>
    <div class='coment-header-left'>
      <p class='comment-username'> <%= comment.name %> </p>
      <p class='subcomment-hour'><%= comment.hour %></p>
    </div>
    <div class='coment-header-right'>
      <div class= "likes">
        <p><%= comment.likes.count %></p>
        <%= button_to student_comment_likes_toggle_comment_like_path(student, comment), method: :post do%>
          <%= image_tag("like.svg", class: comment.liked?(current_user) ? 'dislike-svg' : 'like-svg')%>
        <% end %>
      </div>
    </div>
  </div>
  <p> <%= comment.body %> </p>
  <% if comment.files.attached? %>
    <% comment.files.each do |file|%>
      <p class='comment-links'><%= link_to file.filename, rails_blob_path(file, disposition: 'attachment') %></p>
    <% end %>
  <% end %>
  <details>
    <summary class='summary-btn-comment'></summary>
    <hr class='hr-style'/>
    <div class='sub-comment-container'>
      <% comment.answers.each do |answer| %>
        <div class='sub-comment'>
          <div class='subcomment-header'>
            <p class='subcomment-username'> <%= answer.name %> </p>
            <p class='subcomment-hour'><%= answer.hour %></p>
          </div>
          <p> <%= answer.body %> </p>
        </div>
      <% end %>
    </div>
    <%= render partial: "comments/post_sub_comment_form", locals: { comment: comment, student: @student}  %>
  </details>
<% end %>

app/views/comments/_comments.html.erb
<% comments.each do |key,comment_decorator| %>
  <h3> <%= (key.to_date == Date.today ) ? t('.today') : key %> </h3>
  <% comment_decorator.each do |comment| %>
    <%= render partial: "comments/comment", locals: { student: @student, comment: comment, featured: featured } %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [student, Comment.new], data: {controller: 'emojipicker'})do |form| %>
  <div class='comment-input-section' data-controller="files-input">
    <%= form.label :body, t('.comments') %>
    <%= form.text_area :body, placeholder: t('.comment-post-placeholder'), data: {'emojipicker-target': 'textArea'} %>
    <div class='buttom-modal-comment'>    
      <div class='left-bottom-comment'>
        <%= image_tag("smile.svg",class: 'post-comment-svg',data: {'emojipicker-target': 'button',
        action: 'click->emojipicker#openPicker'})%>
        <label>
           <%= image_tag("image.svg",class: 'post-comment-svg') %>
           <span class='button-files'>
           <%= form.file_field :files, multiple: true, accept:  'image/jpg, image/png, application/pdf, application/msword',
           data: {'files-input-target': 'files'}%>
           </span>
        </label>
        <div class='highlight-comment'>
          <%= form.check_box :stand_out , class: 'highlight-checkbox' %>
          <%= form.label t('.highlight'), class: 'highlight-text' %>
        </div>
        <div class='my-picker-comment' data-emojipicker-target='container'></div>
      </div>
        <%= form.submit value: t('.post'), class: 'post-comment' %>
    </div>
    <div class='files-preview'>
      <ul id='list' data-files-input-target="list"></ul>
    </div>
  </div>
<% end %>

app/views/comments/_post_sub_comment_form.html.erb
 <%= form_with(scope: :answer, url: student_comment_answers_path(@student, comment), method: :post) do |form| %>
  <div class='form-subcomment'>
    <%= form.text_area :body, placeholder: "Escribe tu comentario. Recuerda que puedes utilizar '@' para mencionar personas." %>
    <%= button_tag class: 'form-subcomment-button' do %>
      <%= image_tag 'send.svg', alt:'send-subcomment-img'%>
    <% end %>
  </div>
<% end %>