config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'user_sessions/new'
  get 'user_sessions/destroy'

  get 'login', to: 'user_sessions#new'

  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'

  resources :students do
    resources :attendances, only: [:create]
    resources :comments, only: [:create] do
      post 'likes/toggle_comment_like'
      resources :answers, only: [:create]
    end
  end

  resources :users do
    patch 'change_active', to: 'users#change_active'
  end

  resources :posts, only: [:create] do
    post 'likes/toggle_post_like'
    post 'answers/create_post'
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  enum school_grade: { inicial: 0, primaria: 1, secundaria: 2 }

  validates :name, :lastname, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: 'Only letters allowed.' }
  validates :birthday, presence: true
  validates :address, presence: true
  validates :school_grade, presence: true
  validates :currently_studying, inclusion: { in: [true, false] }, presence: true
  def age
    age = Date.today.year - birthday.year
    age -= 1 if Date.today < birthday + age.years

    age
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[edit update destroy show]

  def index
    @presenter = StudentsPresenter.new(params)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.user = current_user
    if @student.save
      redirect_to students_path, notice: t('.notice')
    else
      redirect_to students_path, alert: t('.alert')
    end
  end

  def show
    @presenter ||= StudentsPresenter.new(params, @student)
  end

  def edit
    authorize @student
  end

  def update
    if @student.update(student_params)
      flash[:notice] = t('.notice')
    else
      flash[:alert] = t('.alert')
    end
    redirect_to students_path
  end

  def destroy
    authorize @student
    if @student.destroy
      flash[:notice] = t('.notice')
    else
      flash[:alert] = t('.alert')
    end
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :lastname, :birthday, :address, :school_grade, :currently_studying)
  end

  def set_student
    @student = Student.find(params[:id]).decorate
  end
end

app/views/students/_comments.html.erb
<% comments.each do |key,comment_decorator| %>
  <h3> <%= (key.to_date == Date.today ) ? t('.today') : key %> </h3>
  <% comment_decorator.each do |comment| %>

    <div class="comment <%= "featured" if featured %>">
        <div class='comment-header'>
          <div class='coment-header-left'>
            <p class='comment-username'> <%= comment.name %> </p>
            <p class='subcomment-hour'><%= comment.hour %></p>
          </div>
          <div class='coment-header-right'>
            <div class= "likes">
              <p><%= comment.likes.count %></p>
              <%= button_to student_comment_likes_toggle_comment_like_path(student, comment), method: :post do%>
                <%= image_tag("like.svg", class: comment.liked?(current_user) ? 'dislike-svg' : 'like-svg')%>
              <% end %>
            </div>
          </div>
        </div>
        <p> <%= comment.body %> </p>
      <details>
        <summary class='summary-btn-comment'></summary>
        <hr class='hr-style'/>
        <div class='sub-comment-container'>
          <% comment.subcomments.each do |subcomment| %>
            <div class='sub-comment'>
              <div class='subcomment-header'>
                <p class='subcomment-username'> <%= subcomment.name %> </p>
                <p class='subcomment-hour'><%= subcomment.hour %></p>
              </div>
              <p> <%= subcomment.body %> </p>
            </div>
          <% end %>
        </div>
        <%= render partial: "comments/post_sub_comment_form", locals: { comment: comment, student: @student}  %>
      </details>
    </div>
  <% end %>
<% end %>

app/views/students/_edit_student_form.html.erb
<%= form_with model: @student, method: "patch" do |form| %>
  <div class="form-field">
    <%= form.label t('.name') %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label t('.lastname')  %>
    <%= form.text_field :lastname %>
  </div>
  <div class="form-field">
    <%= form.label t('.birthday')  %>
    <%= form.date_field :birthday, max: Date.today %>
  </div>
  <div class="form-field">
    <%= form.label t('.address')  %>
    <%= form.text_field :address %>
  </div>
  <div class="form-field">
    <%= form.label t('.school_grade')  %>
    <%= form.select :school_grade, Student.school_grades.keys%>
  </div>
  <div>
    <%= form.label t('.currently_studying') %>
    <div class='radio-buttons'>
      <div>
        <%= form.radio_button :currently_studying, true %>
        <%= form.label t('.radio-yes')  %>
      </div>
      <div>
        <%= form.radio_button :currently_studying, false %>
        <%= form.label 'No' %>
      </div>
    </div>
  </div>
  <%= form.submit t('.register'), class: 'login-button'  %> 
  </div>
<% end %> 

app/views/students/_header.html.erb
<% unless current_user %>  
  <div class= "header">
    <div class= "header-link">
      <%= link_to login_path() do %>
        <%= t('.login') %>
      <% end %>
    </div>
    <div class= "header-link">
      <%=link_to new_user_path() do%>
        <%= t('.register') %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="header header-logged">
    <div class="user-header">
      <h2><%= current_user[:name] %></h2>
    </div>
    <div class= "header-link">
      <%=link_to students_path() do%>
        <%= t('.users_list') %>
      <% end %>
    </div>
    <div class="header-link">
        <%= link_to t('.logout') , :logout , data: { turbo_method: "post" } %>
    </div>
  </div>
<% end %>

app/views/students/_new_student_form.html.erb
<%= form_with model: @student, method: :post do |form| %>
  <div class="form-field">
    <%= form.label t('.name') %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label t('.lastname')  %>
    <%= form.text_field :lastname %>
  </div>
  <div class="form-field">
    <%= form.label t('.birthday')  %>
    <%= form.date_field :birthday, max: Date.today %>
  </div>
  <div class="form-field">
    <%= form.label t('.address')  %>
    <%= form.text_field :address %>
  </div>
  <div class="form-field">
    <%= form.label t('.school_grade')  %>
    <%= form.select :school_grade, Student.school_grades.keys%>
  </div>
  <div>
    <%= form.label t('.currently_studying') %>
    <div class='radio-buttons'>
      <div>
        <%= form.radio_button :currently_studying, true %>
        <%= form.label t('.radio-yes')  %>
      </div>
      <div>
        <%= form.radio_button :currently_studying, false %>
        <%= form.label 'No' %>
      </div>
    </div>
  </div>
  <%= form.submit t('.register'), class: 'login-button'  %> 
<% end %> 

app/views/students/_student_list.erb
<div class="table-container">
  <table class='table-class'>
    <thead>
      <tr class="table-head">
        <th> <%= t('.students')%> </th>        
        <th> <%= t('.age')%>  </th>
        <th> <%= t('.school_grade')%> </th>
        <th> <%= t('.currently_studying')%> </th>
      </tr>
    </thead>
    <tbody>
      <% @presenter.students.each do |student| %>
        <tr class="tr-row-data">
          <td><%= link_to student.full_name, student, class:'student-link' %></td>
          <td><%= student.age %></td>
          <td><%= student.school_grade_capitalize %></td>
          <td><%= student.currently_studying_humanized %></td>
          <td>
            <div class='table-button-center'>
              <% if policy(student).edit? %>
                <%= button_to edit_student_path(student), data: { turbo_frame: 'modal' }, method: :get do %>
                  <%= image_tag 'Edit.svg', alt: 'edit button', class: 'user-list-edit-img' %>
                <% end %>
            </div>
          </td>
          <td>
            <div class='table-button-center'>
          <%= button_to student_path(student),method: :delete,  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do%>
            <%= image_tag( "Delete.svg", class: 'student-pen-icon') %>
          <% end %>             
            </div>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pagy">
  <%== pagy_nav(pagy) %>
</div>

app/views/students/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render TurboModalComponent.new do %>
    <%= tag.div data: { controller: "turbo-modal" } do %>
      <div class="modal">
        <div class="container-modal"> 
          <div class="modal-title">
            <h1> <%= t('.edit_student') %> </h1>
          </div>
          <div class = "modal-form">
            <%= render "edit_student_form", student: @student %>
          </div>
        </div> 
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/students/index.html.erb
<div class='users-list-index''>

  <div class='users-list-filter-section'>
    <div>
      <%=link_to students_path do%>
        <%= t('.students_list') %>
      <% end %>
    </div>
    <div>
      <%=link_to users_path do%>
        <%= t('.users_list') %>
      <% end %>
    </div>

    <div class="user-list-form">
      <%= form_with(html:{class: "form-user-list"},model: @filter, url: users_path, method: :get) do |form| %>
      <div>
        <%= button_tag :submit, class: 'user-list-filter-button' do %>
          <i class='user-list-search-icon'></i>
        <% end %>
      </div>
      <div class= "user-list-search-input">
        <%= form.text_field :name, placeholder: params[:name] %>
      </div> 
      <% end %>
      <div class="user-list-new-user-button">
        <%= button_to new_student_path(), data: { turbo_frame: 'modal' }, method: :get do %>
          <%= image_tag 'New-user.svg', alt:'new-user-img'%>
          <span><%= t('.new_student')%></span>
        <% end %>
      </div>
    </div>
  </div>
  <%= render partial: 'student_list', locals: {records: @presenter.students, pagy: @presenter.pagy_data}%>
</div> 

app/views/students/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render TurboModalComponent.new do %>
    <%= tag.div data: { controller: "turbo-modal" } do %>
      <div class="modal">
        <div class="container-modal"> 
          <div class="modal-title">
            <h1> <%= t('.create-student')%> </h1>
          </div>
          <div class="modal-form">
            <%= render "new_student_form", student: @student %>
          </div>
        </div> 
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/students/show.html.erb
<div class='show-container'>
  <div class="user-container">
    <div class='show-header'>
      <h2> <%= link_to t('.student'), students_path %> </h2>
      <h2> > </h2>
      <h2 class='light-blue-color'> <%= @student.full_name %> </h2>
    </div>
    <h1> <%= @student.name %> <%= @student.lastname %>  </h1>
    <div class="student-data">
      <h2 class='light-blue-color'> <%= t('.student-data')%> </h2>
        <div>
          <h3> <%= t('.birthday')%>  </h3>
          <p> <%= @student.birthday %> </p>
        </div>
        <div>
          <h3> <%= t('.address')%> </h3>
          <p> <%= @student.address %> </p>
        </div>
        <div>
          <h3> <%= t('.school_grade')%>  </h3>
          <p> <%= @student.school_grade_capitalize %> </p>
        </div>
        <div>
          <h3> <%= t('.currently_studying')%>  </h3>
          <p> <%= @student.currently_studying_humanized %> </p>
        </div> 
    </div>
  </div>
  <div class='comments-container'>
    <%= render partial: "comments/form", locals: { student: @student } %>
    <div class='comments'>
      <% if @presenter.comments.any? %>
        <h2> <%= t('.featured_comments') %> </h2>
        <%= render partial: "comments/comments", locals: { student: @student, comments: @presenter.grouped_comments(true), featured: true } %>
        <h2> <%= t('.comments') %> </h2>
        <%= render partial: "comments/comments", locals: { student: @student , comments: @presenter.grouped_comments(false), featured: false } %>
      <% else %>
        <p> <%= t('.no_comments') %>  </p>
      <% end %>
    <div>
  </div>
</div>