config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'user_sessions/new'
  get 'user_sessions/destroy'

  get 'login', to: 'user_sessions#new'

  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'

  resources :students do
    resources :attendances, only: [:create]
    resources :comments, only: [:create] do
      post 'likes/toggle_comment_like'
      resources :answers, only: [:create]
    end
  end

  resources :users do
    patch 'change_active', to: 'users#change_active'
  end

  resources :posts, only: [:create] do
    post 'likes/toggle_post_like'
    post 'answers/create_post'
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :students
  has_many :comments
  has_many :answers
  has_many :likes, dependent: :destroy

  enum rol: { colaborador: 0, administrador: 1 }

  validates :name, :lastname, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: 'Only letters allowed.' }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Formato de email incorrecto.' },
                    uniqueness: true, presence: true
  validate :forbid_changing_email, on: :update
  validates :password, length: { minimum: 3 }, if: :new_record?
  validates_confirmation_of :password

  private

  def forbid_changing_email
    errors.add :email, 'can not be changed!' if email_changed?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_frame_response, only: %i[new edit]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    authorize User
    @filter = UserFilter.new(User.all, filter_params)
    @users  = @filter.call.order(:created_at)
    flash.now[:error] = t('.warning') if @users.empty?
    @pagy, @records = pagy(@users)
  end

  def edit
    authorize User
  end

  def new
    if current_user
      @user = User.new
    else
      redirect_to login_path
    end
  end

  def create
    if current_user
      @user = User.new(user_create_params)
      if @user.save
        flash[:notice] = t('.notice')
        redirect_to users_path
      else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to new_user_path
      end
    else
      redirect_to login_path
    end
  end

  def update
    authorize User
    @user.update(user_params)
    if @user.save
      flash[:notice] = t('.notice')
    else
      @user.errors
    end
    redirect_to users_path
  end

  def change_active
    authorize User
    @user = User.find(params[:user_id])
    @user.active = params[:user][:active]
    if @user.save
      flash[:notice] = t('.notice')
    else
      flash[:error] = @user.errors.full_messages.to_sentence
    end
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_create_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                 :lastname, :rol).except(:password_confirmation)
  end

  def user_params
    params.require(:user).permit(:name, :email, :lastname, :rol)
  end

  def filter_params
    params.fetch(:user_filter, {}).permit(
      :name
    )
  end

  def ensure_frame_response
    return unless Rails.env.development?

    redirect_to users_path unless turbo_frame_request?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user_form.html.erb
<%= render "msg", flash: flash  %>
<%= form_with model: @user, method: "patch" do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>
  <div class="form-field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>
  <div class="form-field">
    <%= form.label :email %>
    <%= form.text_field :email, readonly: true %>
  </div>
  <div class="form-field">
  <%= form.label :rol %>
  <%= form.select :rol, User.rols.keys %>
</div>
  <div class="register-button">
    <%= form.submit "Actualizar usuario" %> 
  </div>
<% end %> 

app/views/users/_form.html.erb
<%= render "msg", flash: flash  %>
<%= form_with model: @user, method: :post do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>
  <div class="form-field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="form-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="form-field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="register-button">
    <%= form.submit "Registrarme" %> 
    <%= button_to do %>
        <%= image_tag "logo.png", class:'google-logo' ,alt: "Google logo" %>
        <%= t('.button-google') %>
    <% end %> 
  </div>
<% end %> 

app/views/users/_header.html.erb
<% unless current_user %>  
  <div class= "header">
    <div class= "header-link">
      <%= link_to login_path() do %>
        <%= t('.login') %>
      <% end %>
    </div>

    <div class= "header-link">
      <%=link_to new_user_path() do%>
        <%= t('.register') %>
      <% end %>
    </div>
  <% else %>
  <div class="header header-logged">
    <div class="user-header">
      <h2><%= @current_user[:name] %></h2>
    </div>
    <div class= "header-link">
      <%=link_to users_list_path() do%>
        <%= t('.users_list') %>
      <% end %>
      </div>
      <div class="header-link">
        <%= link_to "Logout", :logout , data: { turbo_method: "post" } %>
      </div>
    <% end %>
</div>

app/views/users/_log_in.html.erb
<div class="log-in-form">
  <div class="title">
    <h1> <%= t '.title' %> </h1>	
  </div>	
  <%= render "msg", flash: flash  %>
  <%= form_with(url: login_path,method: :post) do |form| %>
    <div class="form-field">
      <%= form.label t('.email') %>
      <%= form.text_field :email , placeholder: (t'.email_placeholder')%>
    </div>
    
    <div class="form-field">
      <%= form.label t'.password' %>
      <%= form.password_field :password, placeholder: (t'.password_placeholder'), :required => true %>
    </div>
    
    <div>
      <%= form.check_box :remember %>
      <%= label_tag(:remember, (t".remember")) %>
    </div>
  
    <div class="log-in-button">
        <%= form.submit (t".login")%> 
      <div class="forgot-password">
        <%= link_to do %>
          <%= t('.forgot-password') %>
        <% end %>
      </div>
        <%= button_to do %>
          <%= image_tag "logo.png", class:'google-logo' ,alt: "Google logo" %>
          <%= t('.button-google') %>
        <% end %> 
    </div>
  <% end %> 
</div>

app/views/users/_new_user_form.html.erb
<%= render "msg", flash: flash  %>
<%= form_with model: @user, method: :post do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>
  <div class="form-field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="form-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="form-field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="register-button">
    <%= form.submit "Registrarme" %> 
  </div>
<% end %> 

app/views/users/_users_list.html.erb
<div class="users-table">
  <table>
    <thead>
      <tr class="table-head">
        <th><%= t '.name' %></th>        
        <th><%= t '.lastname' %> </th>
        <th>Email</th>
        <th>Rol</th>
      </tr>
    </thead>
    <tbody>
      <% records.each do |user| %>
        <tr class="table-row">
          <td><%=user.name%></td>
          <td><%=user.lastname %></td>
          <td><%=user.email %></td>
          <td><%=user.rol%></td>
          <td>
            <%= button_to edit_user_path(user), method: :get do %>
              Editar
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  

  <div class="pagy">
    <%== pagy_nav(pagy) %>
  </div>
</div>

app/views/users/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render TurboModalComponent.new do %>
    <%= tag.div data: { controller: "turbo-modal" } do %>
      <div class="user-new-modal">
        <div class="user-new-container-modal"> 
            <div class="modal-title">
              <h1> <%= t('.edit_user') %> </h1>
            </div>
            <div class="user-new-modal-form">
              <%= render "users/partials/edit_user_form", user: @user %>
            </div>
        </div> 
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class='users-list-index'>
  <div class='users-list-filter-section'>
    <div>
      <%=link_to students_path do%>
        <%= t('.students_list') %>
      <% end %>
    </div>
    <div>
      <%=link_to users_path do%>
        <%= t('.users_list') %>
      <% end %>
    </div>

    <div class="user-list-form">
      <%= form_with(html:{class: "form-user-list"},model: @filter, url: users_path, method: :get) do |form| %>
      <div>
        <%= button_tag :submit, class: 'user-list-filter-button' do %>
          <i class='user-list-search-icon'></i>
        <% end %>
      </div>
      <div class= "user-list-search-input">
        <%= form.text_field :name, placeholder: params[:name] %>
      </div> 
      <% end %>
      <div class="user-list-new-user-button">
        <%= button_to new_user_path(), data: { turbo_frame: 'modal' }, method: :get do %>
          <%= image_tag 'New-user.svg', alt:'new-user-img'%>
          <span><%= t('.new_user')%></span>
        <% end %>
      </div>
    </div>
  </div>
  <%== render partial: 'users/partials/users_list', locals: {records: @records, pagy: @pagy} %>
</div>

app/views/users/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render TurboModalComponent.new do %>
    <%= tag.div data: { controller: "turbo-modal" } do %>
      <div class="user-new-modal">
        <div class="user-new-container-modal"> 
          <div class="modal-title">
            <h1> <%= t('.create_user') %> </h1>
          </div>
          <div class="user-new-modal-form">
            <%= render "users/partials/new_user_form", user: @user %>
          </div>
        </div> 
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/users_list.html.erb
<div class='users-list-index'>

  <div class='users-list-filter-section'>
    <div>
      <%=link_to students_path do%>
        <%= t('.students_list') %>
      <% end %>
    </div>
    <div>
      <%=link_to users_list_path do%>
        <%= t('.users_list') %>
      <% end %>
    </div>

    <div class="user-list-form">
      <%= form_with(html:{class: "form-user-list"},model: @filter, url: users_list_path, method: :get) do |form| %>
      <div>
        <%= button_tag :submit, class: 'user-list-filter-button' do %>
          <i class='user-list-search-icon'></i>
        <% end %>
      </div>
      <div class= "user-list-search-input">
        <%= form.text_field :name, placeholder: params[:name] %>
      </div> 
      <% end %>
      <div class="user-list-new-user-button">
        <%= button_to new_user_path(), data: { turbo_frame: 'modal' }, method: :get do %>
          <%= image_tag 'New-user.svg', alt:'new-user-img'%>
          <span>Nuevo Usuario</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="user-list-container-list">
    <div class="user-list-search-msg">
      <% if flash[:notice].present? || flash[:error].present? %>
        <%= render "partials/msg", flash: flash  %>
      <% end %>
    </div>
    <%== render partial: 'users/partials/users_list', locals: {records: @records, pagy: @pagy} %>
  </div>
</div>