config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'user_sessions/new'
  get 'user_sessions/destroy'

  get 'login', to: 'user_sessions#new'

  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'

  resources :students do
    resources :attendances, only: [:create]
    resources :comments, only: [:create] do
      post 'likes/toggle_comment_like'
      resources :answers, only: [:create]
    end
  end

  resources :users do
    patch 'change_active', to: 'users#change_active'
  end

  resources :posts, only: [:create] do
    post 'likes/toggle_post_like'
    post 'answers/create_post'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include DateHelper
  def index
    @presenter = StudentsPresenter.new(params)
    @home_presenter = HomesPresenter.new(params,Post.all.order(created_at: :desc))
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_attendance.html.erb
<section class='section_attendance_complete'>
  <div class='section_attendance'>
    <h1 class="title_attendance"><%= t('.attendance') %></h1>
    <table class="table_attendance">
      <thead>
         <tr>
           <th class='th_attendance_student'><%= t('.student') %></th>
           <th class='th_td_attendance'><abbr title=<%=t('.alumn_present')%>>P</abbr></th>
           <th class='th_td_attendance'><abbr title=<%=t('.alumn_aus')%>>A</abbr></th>
           <th class='th_td_attendance'><abbr title=<%=t('.alumn_ret')%>>R</abbr></th>
         </tr>  
      </thead>
     <tbody>
       <% @presenter.students_all.each do |student| %>
          <tr data-controller='toggle-attendance' data-toggle-attendance-url-value='<%= student_attendances_path(student) %>'>
            <td class='td_attendance_nomap'><%= student.full_name %></td>
            <% Attendance.assistants.values.each do |v| %>
              <td class='th_td_attendance'>
                <%= radio_button_tag "assistant_#{student.id}", v, false, data: {action: 'click->toggle-attendance#toggleSubmit'} %>
              </td>
            <% end %>
          </tr>
       <% end %>
     </tbody>
    </table>
  </div>

  <div class='section_attendance_summary'>
    <table class="table_attendance">
       <tr>
         <th><%= t('.attendance') %></th>
         <td><span class='color_border_blue'>3</span></td>
         <td><span class='color_border_red'>3</td>
         <td><span class='color_border_yellow'>3</td>
       </tr>
       <tr>
          <th><%= t('.featured') %></th>
          <td COLSPAN=3><span class='color_featured'>25</span></td>
       </tr>
       <tr>
          <th><%= t('.equipment') %></th>
          <td COLSPAN=3>
            <ul class='list_attandance_equip'>
              <li>Camila Tisera</li>
              <li>Gian Lucas</li>
              <li>Nadia</li>
              <li>Moshi</li>
            </ul>
          </td>
       </tr>
    </table>
  </div>
</section>

app/views/home/_post_publication_form.html.erb
<%= form_with url:posts_path(), scope: :publication, method: :post, data: {controller: 'emojipicker'} do |form| %>
  <div class='comment-input-section' data-controller="files-input">
    <%= form.label :body, t('.news') %>
    <%= form.text_area :body, placeholder: t('.publication-post-placeholder'), data: {'emojipicker-target': 'textArea'} %>
    <div class='buttom-modal-comment'>    
      <div class='left-bottom-comment'>
        <%= image_tag("smile.svg",class: 'post-comment-svg',data: {'emojipicker-target': 'button',
        action: 'click->emojipicker#openPicker'})%>
        <label>
           <%= image_tag("image.svg",class: 'post-comment-svg') %>
           <span class='button-files'>
           <%= form.file_field :files, multiple: true, accept:  'image/jpg, image/png, application/pdf, application/msword',
           data: {'files-input-target': 'files'}%>
           </span>
        </label>
        <div class='highlight-comment'>
          <%= form.check_box :stand_out , class: 'highlight-checkbox' %>
          <%= form.label t('.highlight'), class: 'highlight-text' %>
        </div>
        <div class='my-picker-comment' data-emojipicker-target='container'></div>
      </div>
        <%= form.submit t('.post'), class: 'post-comment' %>
    </div>
    <div class='files-preview'>
      <ul id='list' data-files-input-target="list"></ul>
    </div>
  </div>
<% end %>

app/views/home/_post_sub_publication_form.html.erb
 <%= form_with(scope: :answer, url: post_answers_create_post_path(publication), method: :post) do |form| %>
  <div class='form-subcomment'>
    <%= form.text_area :body, placeholder: "Escribe tu publicacion. Recuerda que puedes utilizar '@' para mencionar personas." %>
    <%= button_tag class: 'form-subcomment-button' do %>
      <%= image_tag 'send.svg', alt:'send-subcomment-img'%>
    <% end %>
  </div>
<% end %>

app/views/home/_publication.html.erb
<%= turbo_frame_tag publication, class: featured ? 'comment featured' : 'comment' do %>
  <div class='comment-header'>
    <div class='coment-header-left'>
      <p class='comment-username'> <%= publication.name %></p>
      <p class='subcomment-hour'><%= publication.hour %></p>
    </div>
    <div class='coment-header-right'>
      <div class= "likes">
        <p><%= publication.likes.count %></p>
        <%= button_to  post_likes_toggle_post_like_path(publication), method: :post do%>
          <%= image_tag("like.svg", class: publication.liked?(current_user) ? 'dislike-svg' : 'like-svg')%>
        <% end %>
      </div>
    </div>
  </div>
  <p> <%= publication.body %></p>
  <% if publication.files.attached? %>
    <% publication.files.each do |file|%>
      <p class='comment-links'><%= link_to file.filename, rails_blob_path(file, disposition: 'attachment') %></p>
    <% end %>
  <% end %>
  <details>
    <summary class='summary-btn-comment'></summary>
    <hr class='hr-style'/>
    <div class='sub-comment-container'>
      <% publication.answers.each do |answer| %>
        <div class='sub-comment'>
          <div class='subcomment-header'>
            <p class='subcomment-username'> <%= answer.name %></p>
            <p class='subcomment-hour'><%= answer.hour %></p>
          </div>
          <p> <%= answer.body %></p>
        </div>
      <% end %>
    </div>
    <%= render partial: "home/post_sub_publication_form", locals: { publication: publication}  %>
  </details>
<% end %>

app/views/home/_publications.html.erb
<% publications.each do |key,publication_decorator| %>
  <% publication_decorator.each do |publication| %>
    <%= render partial: "home/publication", locals: { publication: publication, featured: featured } %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<div class='home-container'>
  <div class='home-content-container'>
    <div class='home-header'>
    <div class='home-header-left'>
      <%= link_to '/' do %>
        <p> < </p>
      <% end %>
      <%= link_to '/' do %>
        <p> > </p>
      <% end %>
    </div>
    <div class='home-header-right'>
      <p><%= date %></p>
      <p><%= day %></p>
    </div>
    </div>
    <div class='home-body'>
      <div class='home-body-left'>
        <%= render partial: "home/post_publication_form"%>
        <div class='publications-container'>
          <%= render partial: "home/publications", locals: { publications: @home_presenter.grouped_publications(true), featured: true }%>
          <%= render partial: "home/publications", locals: { publications: @home_presenter.grouped_publications(false), featured: false }%>
        </div>
      </div>
      <div class='home-body-right'>
        <%= render "home/attendance" %>
      </div>
    </div>
  </div>
</div>